apiVersion: v2
name: argo-cd
description: A Helm chart for Argo
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: argo-cd
    version: 5.3.1
    repository: https://argoproj.github.io/argo-helm
