apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-demo.fullname" . }}-svc-stable
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "argo-demo.fullname" . }}-rollouts
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-demo.fullname" . }}-svc-canary
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "argo-demo.fullname" . }}-rollouts
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: {{ include "argo-demo.fullname" . }}-svc-weighted
spec:
  weighted:
    services:
      - name: {{ include "argo-demo.fullname" . }}-svc-stable
        port: 80
      - name: {{ include "argo-demo.fullname" . }}-svc-canary
        port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ template "argo-demo.fullname" . }}-middleware
spec:
  stripPrefix:
    prefixes:
      - /argo/apps
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "argo-demo.fullname" . }}-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/argo/apps`)
      middlewares:
        - name: {{ template "argo-demo.fullname" . }}-middleware
      services:
        - name: {{ include "argo-demo.fullname" . }}-svc-weighted
          kind: TraefikService
