{{- $kubePrometheusStack := index .Values "kube-prometheus-stack" }}
{{- if and $kubePrometheusStack.grafana.enabled $kubePrometheusStack.grafana.sidecar.dashboards.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-middleware-grafana
spec:
  stripPrefix:
    prefixes:
      - /grafana
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-ingressroute-grafana
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/grafana`)
      middlewares:
        - name: {{ template "kube-prometheus-stack.fullname" . }}-middleware-grafana
      services:
        - name: {{ template "kube-prometheus-stack.fullname" . }}-grafana
          port: 80
{{- end }}