apiVersion: v2
name: kube-prometheus-stack
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: kube-prometheus-stack
    version: 39.8.0
    repository: https://prometheus-community.github.io/helm-charts
